version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/components"
    schedule:
      interval: "weekly"
