version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    target-branch: dev
    groups:
      dev:
        patterns:
          - "*"
    labels:
      - "type: Dependencies"
