builds:
  - main: ./cmd/kernel
    id: "vertex-kernel"
    binary: vertex-kernel
    goos:
      - linux
      - darwin
#      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

  - main: ./cmd/main
    id: "vertex"
    binary: vertex
    goos:
      - linux
      - darwin
#      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64

release:
  prerelease: auto
