version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    target-branch: main
    groups:
      main:
        patterns:
          - "*"
    labels:
      - "type: Dependencies"
