version: "3.8"

services:
  vertex:
    image: ghcr.io/vertex-center/vertex-bundle:main
    networks:
      - internal
      - external
    ports:
      - "7500:7500"
      - "7502:7502"
      - "7504:7504"
      - "7506:7506"
      - "7508:7508"
      - "7510:7510"
      - "7512:7512"
      - "7514:7514"
      - "7516:7516"
    environment:
      - VERTEX_ADMIN_ADDR=http://vertex:7500/api
      - VERTEX_AUTH_ADDR=http://vertex:7502/api
      - VERTEX_CONTAINERS_ADDR=http://vertex:7504/api
      - VERTEX_CONTAINERS_KERNEL_ADDR=http://vertex-kernel:7505/api
      - VERTEX_MONITORING_ADDR=http://vertex:7506/api
      - VERTEX_REVERSE_PROXY_ADDR=http://vertex:7508/api
      - VERTEX_SERVICE_EDITOR_ADDR=http://vertex:7510/api
      - VERTEX_SQL_ADDR=http://vertex:7512/api
      - VERTEX_TUNNELS_ADDR=http://vertex:7514/api
      - VERTEX_LOGS_ADDR=http://vertex:7516/api
      - VERTEX_DB_HOST=postgres
      - VERTEX_DB_PORT=5432
      - VERTEX_DB_USER=postgres
      - VERTEX_DB_PASS=vx-pg-pass
    volumes:
      - logs:/live/logs

  vertex-kernel:
    image: ghcr.io/vertex-center/vertex-bundle-kernel:main
    networks:
      - internal
    environment:
      - VERTEX_LOGS_ADDR=http://vertex:7516/api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  client:
    image: ghcr.io/vertex-center/client:main
    networks:
      - external
      - internal
    ports:
      - "7518:80"
    environment:
      - VERTEX_ADMIN_ADDR=http://admin:8080/api
      - VERTEX_AUTH_ADDR=http://auth:8080/api
      - VERTEX_CONTAINERS_ADDR=http://containers:8080/api
      - VERTEX_LOGS_ADDR=http://logs:8080/api
      - VERTEX_MONITORING_ADDR=http://monitoring:8080/api
      - VERTEX_REVERSE_PROXY_ADDR=http://reverseproxy:8080/api
      - VERTEX_SERVICE_EDITOR_ADDR=http://serviceeditor:8080/api
      - VERTEX_SQL_ADDR=http://sql:8080/api
      - VERTEX_TUNNELS_ADDR=http://tunnels:8080/api

  postgres:
    image: postgres:16.1-alpine3.19
    networks:
      - internal
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vx-pg-pass
      - POSTGRES_DBS=admin auth containers
    volumes:
      - ./multidb/setup_postgres.sh:/docker-entrypoint-initdb.d/setup_postgres.sh:ro
      - postgres:/var/lib/postgresql/data

networks:
  external:
  internal:

volumes:
  postgres:
  logs:
