version: "3.8"

services:
  vertex:
    image: vertex-bundle
    build:
      context: ..
      dockerfile: docker/bundle.Dockerfile
      args:
        - APP_KIND=main
    networks:
      - internal
      - external
    ports:
      - "7500:7500"
      - "7502:7502"
      - "7504:7504"
      - "7506:7506"
      - "7508:7508"
      - "7510:7510"
      - "7512:7512"
      - "7514:7514"
      - "7516:7516"
      - "7518:7518"
    environment:
      - VERTEX_ADMIN_ADDR=http://vertex:7500/api
      - VERTEX_ADMIN_KERNEL_ADDR=http://vertex-kernel:7501/api
      - VERTEX_AUTH_ADDR=http://vertex:7502/api
      - VERTEX_CONTAINERS_ADDR=http://vertex:7504/api
      - VERTEX_CONTAINERS_KERNEL_ADDR=http://vertex-kernel:7505/api
      - VERTEX_MONITORING_ADDR=http://vertex:7506/api
      - VERTEX_REVERSE_PROXY_ADDR=http://vertex:7508/api
      - VERTEX_SERVICE_EDITOR_ADDR=http://vertex:7510/api
      - VERTEX_SQL_ADDR=http://vertex:7512/api
      - VERTEX_TUNNELS_ADDR=http://vertex:7514/api
      - VERTEX_LOGS_ADDR=http://vertex:7516/api

  vertex-kernel:
    image: vertex-kernel-bundle
    build:
      context: ..
      dockerfile: docker/bundle.Dockerfile
      args:
        - APP_KIND=kernel
    networks:
      - internal
    environment:
      - VERTEX_LOGS_ADDR=http://vertex:7516/api

networks:
  external:
  internal:
