version: '3.8'

services:
  client:
    build:
      context: ..
      dockerfile: client/docker/Dockerfile

  vertex:
    build:
      context: ../server
      dockerfile: docker/bundle.Dockerfile
      args:
        - APP_KIND=main

  vertex-kernel:
    build:
      context: ../server
      dockerfile: docker/bundle.Dockerfile
      args:
        - APP_KIND=kernel
