version: '3.8'

services:
  client:
    build:
      context: ..
      dockerfile: client/docker/Dockerfile

  vertex:
    build:
      context: ..
      dockerfile: server/docker/bundle.Dockerfile
      args:
        - APP_KIND=main

  vertex-kernel:
    build:
      context: ..
      dockerfile: server/docker/bundle.Dockerfile
      args:
        - APP_KIND=kernel
