version: '3.8'

services:
  client:
    build:
      context: ..
      dockerfile: client/docker/dev.Dockerfile
    volumes:
      - ../client:/app/client
      - ../packages:/app/packages
    ports:
      - "5173:5173"

  vertex:
    build:
      context: ..
      dockerfile: server/docker/bundle.dev.Dockerfile
    environment:
      - APP_KIND=main
    volumes:
      - ../server:/vertex/server

  vertex-kernel:
    build:
      context: ..
      dockerfile: server/docker/bundle.dev.Dockerfile
    environment:
      - APP_KIND=kernel
    volumes:
      - ../server:/vertex/server
