version: "3.8"

services:
  admin:
    image: ghcr.io/vertex-center/vertex-admin:main
    networks:
      - internal
      - external
    ports:
      - "7500:8080"
    environment:
      - VERTEX_LOGS_ADDR=http://logs:8080/api
      - VERTEX_AUTH_ADDR=http://auth:8080/api
      - VERTEX_ADMIN_KERNEL_ADDR=http://admin-kernel:8080/api

  admin-kernel:
    image: ghcr.io/vertex-center/vertex-admin-kernel:main
    networks:
      - internal
    environment:
      - VERTEX_LOGS_ADDR=http://logs:8080/api

  auth:
    image: ghcr.io/vertex-center/vertex-auth:main
    networks:
      - internal
      - external
    ports:
      - "7502:8080"
    environment:
      - VERTEX_LOGS_ADDR=http://logs:8080/api

  client:
    image: ghcr.io/vertex-center/vertex-client:main
    networks:
      - external
      - internal
    ports:
      - "7518:8080"
      - "6132:6132"
    environment:
      - VERTEX_ADMIN_ADDR=http://admin:8080/api
      - VERTEX_AUTH_ADDR=http://auth:8080/api
      - VERTEX_CONTAINERS_ADDR=http://containers:8080/api
      - VERTEX_LOGS_ADDR=http://logs:8080/api
      - VERTEX_MONITORING_ADDR=http://monitoring:8080/api
      - VERTEX_REVERSE_PROXY_ADDR=http://reverseproxy:8080/api
      - VERTEX_SERVICE_EDITOR_ADDR=http://serviceeditor:8080/api
      - VERTEX_SQL_ADDR=http://sql:8080/api
      - VERTEX_TUNNELS_ADDR=http://tunnels:8080/api

  containers:
    image: ghcr.io/vertex-center/vertex-containers:main
    networks:
      - internal
      - external
    ports:
      - "7504:8080"
    environment:
      - VERTEX_LOGS_ADDR=http://logs:8080/api
      - VERTEX_AUTH_ADDR=http://auth:8080/api
      - VERTEX_CONTAINERS_KERNEL_ADDR=http://containers-kernel:8080/api

  containers-kernel:
    image: ghcr.io/vertex-center/vertex-containers-kernel:main
    networks:
      - internal
    environment:
      - VERTEX_LOGS_ADDR=http://logs:8080/api

  monitoring:
    image: ghcr.io/vertex-center/vertex-monitoring:main
    networks:
      - internal
      - external
    ports:
      - "7506:8080"
    environment:
      - VERTEX_LOGS_ADDR=http://logs:8080/api
      - VERTEX_AUTH_ADDR=http://auth:8080/api
      - VERTEX_CONTAINERS_ADDR=http://containers:8080/api

  reverseproxy:
    image: ghcr.io/vertex-center/vertex-reverseproxy:main
    networks:
      - internal
      - external
    ports:
      - "7508:8080"
    environment:
      - VERTEX_LOGS_ADDR=http://logs:8080/api
      - VERTEX_AUTH_ADDR=http://auth:8080/api

  serviceeditor:
    image: ghcr.io/vertex-center/vertex-serviceeditor:main
    networks:
      - internal
      - external
    ports:
      - "7510:8080"
    environment:
      - VERTEX_LOGS_ADDR=http://logs:8080/api
      - VERTEX_AUTH_ADDR=http://auth:8080/api

  sql:
    image: ghcr.io/vertex-center/vertex-sql:main
    networks:
      - internal
      - external
    ports:
      - "7512:8080"
    environment:
      - VERTEX_LOGS_ADDR=http://logs:8080/api
      - VERTEX_AUTH_ADDR=http://auth:8080/api
      - VERTEX_CONTAINERS_ADDR=http://containers:8080/api

  tunnels:
    image: ghcr.io/vertex-center/vertex-tunnels:main
    networks:
      - internal
      - external
    ports:
      - "7514:8080"
    environment:
      - VERTEX_LOGS_ADDR=http://logs:8080/api
      - VERTEX_AUTH_ADDR=http://auth:8080/api
      - VERTEX_CONTAINERS_ADDR=http://containers:8080/api

  logs:
    image: ghcr.io/vertex-center/vertex-logs:main
    networks:
      - internal

networks:
  external:
  internal:
