name: Deploy to Firebase Hosting

on: [ workflow_dispatch ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install
        run: npm ci

      - name: Install Playwright
        run: npx playwright@1.39.0 install --with-deps

      - name: Download OpenAPI specs
        run: ./scripts/download-openapi-specs.sh

      - name: Build
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VERTEX_CENTER }}'
          channelId: live
          projectId: vertex-center
