version: '3.8'

services:
  client:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "6133:80"
    environment:
      VERTEX_SQL_ADDR: http://localhost:7512/api
      VERTEX_REVERSE_PROXY_ADDR: http://localhost:7508/api
      VERTEX_SERVICE_EDITOR_ADDR: http://localhost:7510/api
      VERTEX_CONTAINERS_ADDR: http://localhost:7504/api
      VERTEX_ADMIN_ADDR: http://localhost:7500/api
      VERTEX_AUTH_ADDR: http://localhost:7502/api
      VERTEX_TUNNELS_ADDR: http://localhost:7514/api
      VERTEX_MONITORING_ADDR: http://localhost:7506/api
