name: Release (beta)

on:
  push:
    tags:
      - "v*-beta*"

permissions:
  contents: write

jobs:
  pre-checks:
    name: Run pre-checks
    uses: ./.github/workflows/call-pre-checks.yml

  release:
    name: Release
    needs: pre-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          check-latest: true
          cache: true

      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trigger-docapi:
    needs: release
    name: Generate DocAPI
    uses: ./.github/workflows/call-docapi.yml
    secrets:
      token: ${{ secrets.PAT }}
