name: Build

on: [workflow_call, workflow_dispatch]

jobs:
  build-bundle:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - GOOS: darwin
            GOARCH: amd64
            os: macos-latest
          - GOOS: darwin
            GOARCH: arm64
            os: macos-latest

          - GOOS: linux
            GOARCH: amd64
            os: ubuntu-latest
          - GOOS: linux
            GOARCH: arm64
            os: ubuntu-latest
          - GOOS: linux
            GOARCH: arm
            os: ubuntu-latest
          - GOOS: linux
            GOARCH: "386"
            os: ubuntu-latest

          - GOOS: windows
            GOARCH: amd64
            os: windows-latest
          - GOOS: windows
            GOARCH: arm64
            os: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build
        run: |
          go build -o vertex ./cmd/main
          go build -o vertex-kernel ./cmd/kernel
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}

  build-microservices:
    name: Build Microservices
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-id:
          - admin
          - auth
          - client
          - containers
          - logs
          - monitoring
          - reverseproxy
          - serviceeditor
          - sql
          - tunnels
        app-kind:
          - main
        include:
          - app-id: admin
            app-kind: kernel
          - app-id: containers
            app-kind: kernel
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build
        run: |
          go build -o vertex ./apps/${{ matrix.app-id }}/cmd/${{ matrix.app-kind }}
