name: Trigger docapi

on:
  workflow_call:
    secrets:
      token:
        required: true

permissions:
  contents: write

jobs:
  trigger-docapi:
    name: Trigger docapi
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docapi
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Content-Type: application/javascript" \
          -H "Authorization: Bearer ${{ secrets.token }}" \
          https://api.github.com/repos/vertex-center/openapi/dispatches \
          -d '{"event_type":"docapi","client_payload":{"ref":"${{ github.ref }}"}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
