name: Build Docker

on: [workflow_call, workflow_dispatch]

jobs:
  build-docker-bundle:
    name: Build Docker bundled
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-kind: [main, kernel]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          context: .
          file: docker/bundle.Dockerfile
          build-args: |
            APP_KIND=${{ matrix.app-kind }}
          tags: ${{ github.repository }}:latest

  build-docker-microservices:
    name: Build Docker microservices
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only build microservices for two cases, just to
        # ensure that the micro.Dockerfile is working.
        # If there is a problem with a specific app, it will fail
        # in the call-build step.
        include:
          - app-id: admin
            app-kind: main
          - app-id: containers
            app-kind: kernel
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          context: .
          file: docker/micro.Dockerfile
          build-args: |
            APP_ID=${{ matrix.app-id }}
            APP_KIND=${{ matrix.app-kind }}
          tags: ${{ github.repository }}:latest
