name: Client (release)

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn workspace @vertex-center/client build

      - name: Add version file
        run: echo ${{ github.ref_name }} > ./client/dist/version.txt

      - name: Create .zip
        run: zip client.zip ./client/dist -r

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: client.zip
