name: Client (dev)

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/client-dev.yml'
      - 'client/**'
      - 'packages/**'

  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    name: Build and push container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/client

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
          context: .
          file: client/docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64,linux/arm
          no-cache: true

  promote-docker:
    name: Promote Docker images
    runs-on: ubuntu-latest
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Promote images
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/client:${{ format('{0}', github.ref_name) }}
          docker tag ghcr.io/${{ github.repository_owner }}/client:${{ format('{0}', github.ref_name) }} ghcr.io/${{ github.repository_owner }}/client:latest
          docker push ghcr.io/${{ github.repository_owner }}/client:latest
