name: Components

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/components.yml'
      - 'packages/components/**'

  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          corepack enable
          yarn --frozen-lockfile

      - name: Run tests
        run: yarn workspace @vertex-center/components test
