name: Deploy to Firebase Hosting

on: [ workflow_dispatch ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npx playwright install
          npm ci && npm run build

      - name: Download OpenAPI specs
        run: |
          git clone https://github.com/vertex-center/openapi.git vertex-openapi
          cp vertex-openapi/openapi.vertex.dev.yml api/api/next/openapi.yml
          cp vertex-openapi/openapi.kernel.dev.yml api/kernel-api/next/openapi.yml

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VERTEX_CENTER }}'
          channelId: live
          projectId: vertex-center
