name: Development

on:
  push:
    branches:
      - dev
      - hotfix
  pull_request:
    branches:
      - dev
      - hotfix
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/call-build.yml
  build-docker:
    uses: ./.github/workflows/call-build-docker.yml
  test:
    uses: ./.github/workflows/call-test.yml
  lint:
    uses: ./.github/workflows/call-lint.yml
