name: Development

on:
  push:
    branches:
      - dev
      - hotfix
  pull_request:
    branches:
      - dev
      - hotfix
  workflow_call:

permissions:
  contents: write

jobs:
  pre-checks:
    name: Run pre-checks
    uses: ./.github/workflows/call-pre-checks.yml

  trigger-docapi:
    name: Trigger DocAPI Generation
    needs: pre-checks
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/call-docapi.yml
    secrets:
      token: ${{ secrets.PAT }}
