name: Development

on:
  push:
    branches:
      - dev
      - hotfix
  pull_request:
    branches:
      - dev
      - hotfix
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - GOOS: darwin
            GOARCH: amd64
            os: macos-latest
          - GOOS: darwin
            GOARCH: arm64
            os: macos-latest

          - GOOS: linux
            GOARCH: amd64
            os: ubuntu-latest
          - GOOS: linux
            GOARCH: arm64
            os: ubuntu-latest
          - GOOS: linux
            GOARCH: arm
            os: ubuntu-latest
          - GOOS: linux
            GOARCH: "386"
            os: ubuntu-latest

          - GOOS: windows
            GOARCH: amd64
            os: windows-latest
          - GOOS: windows
            GOARCH: arm64
            os: windows-latest
          - GOOS: windows
            GOARCH: arm
            os: windows-latest
          - GOOS: windows
            GOARCH: "386"
            os: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build
        run: |
          go build -o vertex ./cmd/main
          go build -o vertex-kernel ./cmd/kernel
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}

  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ github.repository }}:latest

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Test
        run: go test -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          args: --timeout 5m
