name: Docs

on:
  pull_request:
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
      - 'packages/**'

  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build_deploy:
    name: ${{ github.ref == 'refs/heads/main' && 'Build and deploy' || 'Build' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Enable corepack
        run: corepack enable

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Install Playwright
        run: yarn workspace @vertex-center/docs dlx playwright install --with-deps chromium

      - name: Download OpenAPI specs
        run: ./docs/scripts/download-openapi-specs.sh

      - name: Build
        run: yarn workspace @vertex-center/docs build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: github.ref == 'refs/heads/main'
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VERTEX_CENTER }}'
          channelId: live
          projectId: vertex-center
