name: Docs

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
      - 'packages/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Enable corepack
        run: corepack enable

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Install Playwright
        run: yarn workspace @vertex-center/docs dlx playwright install --with-deps chromium

      - name: Download OpenAPI specs
        run: ./docs/scripts/download-openapi-specs.sh

      - name: Build
        run: yarn workspace @vertex-center/docs build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VERTEX_CENTER }}'
          channelId: live
          projectId: vertex-center
