name: Pull Request

on: [pull_request_target]

jobs:
  add-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: actions/labeler@v5
