name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  publish:
    needs: build
    strategy:
      matrix:
        include:
          - registry: "https://registry.npmjs.org/"
            token: NPM_TOKEN
          - registry: "https://npm.pkg.github.com/"
            token: GITHUB_TOKEN

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: ${{ matrix.registry }}

      - name: Publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.token] }}
