name: SonarCloud

on:
  push:
    branches:
      - dev
      - hotfix
      - main
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Run SonarCloud
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout (PR)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Checkout (Push)
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Run test coverage
        run: |
          go test -coverprofile=coverage.out ./...

      - name: Run test json
        run: go test -json ./... > report.json

      - name: Run Scan (Push)
        if: github.event_name == 'push'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Scan (PR)
        if: github.event_name == 'pull_request_target'
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
